---
title: "Coefficients in ANOVA analysis"
author: "Lucy"
date: "10/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
experiment.data <- data.frame( Block = factor(rep(paste0("Field", 1:8),3)), 
                               Fertilizer = factor(rep(c("Control", "Absent", "High"), each = 8)),
                               yields = c(9.3, 8.7, 9.3, 9.5, 9.9, 8.9, 8.3, 9.1,
                                          8.7, 7.1, 8.2, 8.9, 9.1, 8.0, 6.2, 7.0,
                                          10.0, 9.1, 10.4, 10.0, 10.8, 9.0, 8.9, 8.1))
experiment.data 
options(contrasts=c("contr.sum","contr.poly"))
lm.Sum2Zero <- lm(yields ~ Fertilizer + Block, data = experiment.data)
lm.Sum2Zero
```

* $\widehat{\mu} = \bar{y}_{..} = 8.8542$
* $\widehat{\tau}_1 = \bar{y}_{.1} -\bar{y}_{..} = -0.9542$
* $\widehat{\tau}_2 =  \bar{y}_{.2} -\bar{y}_{..} = 0.2708$
* $\widehat{\tau}_3 =  \bar{y}_{.3} -\bar{y}_{..}= -(\widehat{\tau}_1 + \widehat{\tau}_2) = -(-0.9542 + 0.2708) = 0.6834$
* $\widehat{\beta}_1 = 0.4792$
* ...
* $\widehat{\beta}_8 = -(\widehat{\beta}_1+\ldots+\widehat{\beta}_7)$

